export const CITIES = [
  { name: 'Temecula', state: 'CA', zip: '92590', priority: 'primary' as const, businessCount: 2598 },
  { name: 'Murrieta', state: 'CA', zip: '92562', priority: 'primary' as const, businessCount: 1560 },
  { name: 'Hemet', state: 'CA', zip: '92543', priority: 'secondary' as const, businessCount: 937 },
  { name: 'Menifee', state: 'CA', zip: '92584', priority: 'secondary' as const, businessCount: 725 },
  { name: 'Fallbrook', state: 'CA', zip: '92028', priority: 'secondary' as const, businessCount: 692 },
  { name: 'Lake Elsinore', state: 'CA', zip: '92530', priority: 'secondary' as const, businessCount: 617 },
  { name: 'Perris', state: 'CA', zip: '92570', priority: 'secondary' as const, businessCount: 522 },
  { name: 'Wildomar', state: 'CA', zip: '92595', priority: 'tertiary' as const, businessCount: 218 },
  { name: 'Winchester', state: 'CA', zip: '92596', priority: 'tertiary' as const, businessCount: 94 },
  { name: 'Sun City', state: 'CA', zip: '92585', priority: 'tertiary' as const, businessCount: 38 },
  { name: 'Canyon Lake', state: 'CA', zip: '92587', priority: 'tertiary' as const, businessCount: 21 },
];

export const PAYMENT_LINKS = {
  verified_monthly: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993ca3644f21fbd42d4a6ae',
  verified_quarterly: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993cb0944f21ff36fd4a7fe',
  verified_6month: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993cf59e6b9113225e77aca',
  verified_annual: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993cfd485a7d802ef9dae1c',
  partner_monthly: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d000e6b9111cffe77bf2',
  partner_quarterly: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d02a85a7d81c3a9dae5a',
  partner_6month: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d05f44f21f39cad4ae94',
  partner_annual: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d08485a7d893579daef6',
  elite_monthly: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d0bee6b9110bd7e77cb5',
  elite_quarterly: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d0fb44f21fb10dd4af40',
  elite_6month: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d14d44f21f454bd4afbe',
  elite_annual: 'https://lk.platinumdirectorytemeculavalley.com/payment-link/6993d18844f21fd42fd4b055',
};

export const PRICING = {
  verified_platinum: {
    monthly: { price: 99, display: '$99/mo' },
    quarterly: { price: 267, monthly: 89, display: '$267/quarter ($89/mo)', savings: '10%' },
    sixMonth: { price: 505, monthly: 84.15, display: '$505/6mo ($84.15/mo)', savings: '15%' },
    annual: { price: 950, monthly: 79.17, display: '$950/year ($79.17/mo)', savings: '20%' },
  },
  platinum_partner: {
    monthly: { price: 799, display: '$799/mo' },
    quarterly: { price: 2157, monthly: 719, display: '$2,157/quarter ($719/mo)', savings: '10%' },
    sixMonth: { price: 4075, monthly: 679, display: '$4,075/6mo ($679/mo)', savings: '15%' },
    annual: { price: 7670, monthly: 639, display: '$7,670/year ($639/mo)', savings: '20%' },
  },
  platinum_elite: {
    monthly: { price: 3500, display: '$3,500/mo' },
    quarterly: { price: 9450, monthly: 3150, display: '$9,450/quarter ($3,150/mo)', savings: '10%' },
    sixMonth: { price: 17850, monthly: 2975, display: '$17,850/6mo ($2,975/mo)', savings: '15%' },
    annual: { price: 33600, monthly: 2800, display: '$33,600/year ($2,800/mo)', savings: '20%' },
  },
};

export const PLATFORM_FEES = {
  free: { affiliateFee: 0.05, platformFee: 0.30, businessKeeps: 0.65 },
  verified_platinum: { affiliateFee: 0.05, platformFee: 0.25, businessKeeps: 0.70 },
  platinum_partner: { affiliateFee: 0.05, platformFee: 0.20, businessKeeps: 0.75 },
  platinum_elite: { affiliateFee: 0.05, platformFee: 0.20, businessKeeps: 0.75 },
};

export const CATEGORIES = [
  { name: 'Restaurants & Dining', icon: 'UtensilsCrossed', order: 1, slug: 'restaurants-dining' },
  { name: 'Wineries & Vineyards', icon: 'Wine', order: 2, slug: 'wineries-vineyards' },
  { name: 'Tours & Attractions', icon: 'Map', order: 3, slug: 'tours-attractions' },
  { name: 'Hotels & Lodging', icon: 'Hotel', order: 4, slug: 'hotels-lodging' },
  { name: 'Health & Wellness', icon: 'Heart', order: 5, slug: 'health-wellness' },
  { name: 'Shopping & Retail', icon: 'ShoppingBag', order: 6, slug: 'shopping-retail' },
  { name: 'Professional Services', icon: 'Briefcase', order: 7, slug: 'professional-services' },
  { name: 'Home Services', icon: 'Wrench', order: 8, slug: 'home-services', homepageLabel: 'Home Improvement' },
  { name: 'Automotive', icon: 'Car', order: 9, slug: 'automotive', homepageLabel: 'Auto Services & Detailing' },
  { name: 'Beauty & Personal Care', icon: 'Sparkles', order: 10, slug: 'beauty-personal-care' },
  { name: 'Real Estate & Property', icon: 'Home', order: 11, slug: 'real-estate-property' },
  { name: 'Arts & Entertainment', icon: 'Music', order: 12, slug: 'arts-entertainment', homepageLabel: 'Events & Entertainment' },
  { name: 'Education & Childcare', icon: 'GraduationCap', order: 13, slug: 'education-childcare' },
  { name: 'Pets & Animals', icon: 'PawPrint', order: 14, slug: 'pets-animals' },
  { name: 'Technology & IT', icon: 'Monitor', order: 15, slug: 'technology-it' },
  { name: 'Local Artisans & Crafts', icon: 'Palette', order: 16, slug: 'local-artisans-crafts' },
  { name: 'Business to Business', icon: 'Building2', order: 17, slug: 'business-to-business' },
  { name: 'Nonprofit & Community', icon: 'Users', order: 18, slug: 'nonprofit-community' },
  { name: 'Luxury Accommodations', icon: 'Crown', order: 19, slug: 'luxury-accommodations' },
  { name: 'Old Town Dining', icon: 'Store', order: 20, slug: 'old-town-dining' },
];

export const TIER_CARDS = {
  free: {
    name: 'FREE',
    tagline: 'Always free, no billing',
    icon: 'MapPin',
    trafficSources: ['Organic Traffic', 'Smart Offers Affiliate Traffic'],
    monthlyLeads: 'Self-managed',
    smartOfferFee: 0.30,
    badge: null,
  },
  verified_platinum: {
    name: 'VERIFIED PLATINUM',
    tagline: 'Get found locally',
    icon: 'Shield',
    trafficSources: ['Organic SEO', 'Directory Traffic', 'Social Discovery'],
    monthlyLeads: 'AI-enhanced profile',
    smartOfferFee: 0.25,
    badge: null,
  },
  platinum_partner: {
    name: 'PLATINUM PARTNER',
    tagline: 'Dominate your market',
    icon: 'Zap',
    trafficSources: ['Organic SEO', 'Paid Ads', 'Email Marketing', 'SMS Campaigns', 'Social Media'],
    monthlyLeads: '25 guaranteed leads/month',
    smartOfferFee: 0.20,
    badge: 'MORE PROFITABLE',
  },
  platinum_elite: {
    name: 'PLATINUM ELITE',
    tagline: 'Exclusive dominance + unlimited AI calls',
    icon: 'Crown',
    trafficSources: ['All Channels', 'Dedicated Campaigns', 'Category Ownership', 'Premium Placement'],
    monthlyLeads: 'Category exclusivity + unlimited leads',
    smartOfferFee: 0.20,
    badge: 'MOST PROFITABLE',
  },
};

export const FEATURE_MATRIX = [
  {
    category: 'Core Directory & Profile',
    features: [
      { name: 'Basic Business Listing', free: true, verified: true, partner: true, elite: true },
      { name: 'Photo & Media Gallery', free: false, verified: true, partner: true, elite: true },
      { name: 'Business Hours & Map Integration', free: false, verified: true, partner: true, elite: true },
      { name: 'Verified Badge & Priority Search Ranking', free: false, verified: true, partner: true, elite: true },
      { name: 'Customer Reviews & Ratings', free: false, verified: true, partner: true, elite: true },
      { name: 'Video Gallery & YouTube', free: false, verified: true, partner: true, elite: true },
      { name: 'Menu/Price List Display', free: false, verified: true, partner: true, elite: true },
      { name: 'Online Booking Widget', free: false, verified: true, partner: true, elite: true },
      { name: 'Testimonials & Press Section', free: false, verified: true, partner: true, elite: true },
      { name: 'Custom Badges & Certifications', free: false, verified: true, partner: true, elite: true },
      { name: 'Amenities & Services Tags', free: false, verified: true, partner: true, elite: true },
      { name: 'Category Tags', free: false, verified: true, partner: true, elite: true },
      { name: 'Custom Branding', free: false, verified: true, partner: true, elite: true },
    ],
  },
  {
    category: 'AI & Automation',
    features: [
      { name: 'AI Personal Assistant (24/7)', free: false, verified: true, partner: true, elite: true },
      { name: 'AI Call Assistant', free: false, verified: false, partner: '$0.15/min', elite: 'UNLIMITED' },
      { name: 'Lead Capture Forms', free: false, verified: true, partner: true, elite: true },
      { name: 'Managed Lead Routing', free: false, verified: false, partner: true, elite: true },
      { name: 'Email Auto-Responders', free: false, verified: true, partner: true, elite: true },
      { name: 'Automated Follow-Ups', free: false, verified: false, partner: true, elite: true },
      { name: 'AI Appointment Scheduling', free: false, verified: false, partner: true, elite: true },
      { name: 'Custom Workflow Automation', free: false, verified: false, partner: true, elite: true },
      { name: 'CRM Integration', free: false, verified: false, partner: true, elite: true },
      { name: 'Competitive Intelligence', free: false, verified: false, partner: true, elite: true },
      { name: 'AI Content Generation', free: false, verified: false, partner: true, elite: true },
      { name: 'AI Financial Chatbot', free: false, verified: false, partner: true, elite: true },
    ],
  },
  {
    category: 'Smart Offers & Marketing',
    features: [
      { name: 'Create Smart Offers', free: false, verified: true, partner: true, elite: true },
      { name: 'Point-of-Sale Connect', free: false, verified: false, partner: true, elite: true },
      { name: 'Online Payments (Collection)', free: false, verified: false, partner: true, elite: true },
      { name: 'Task Deals', free: false, verified: false, partner: true, elite: true },
      { name: 'Loyalty Programs', free: false, verified: false, partner: true, elite: true },
      { name: 'QR Code Generator', free: false, verified: false, partner: true, elite: true },
      { name: 'Referral Program Building', free: false, verified: false, partner: true, elite: true },
      { name: 'Coupon & Promo Code Management', free: true, verified: true, partner: true, elite: true },
      { name: 'Social Media Scheduler & Auto-Post', free: false, verified: true, partner: true, elite: true },
      { name: 'Google My Business Integration', free: false, verified: true, partner: true, elite: true },
    ],
  },
  {
    category: 'CRM & Customer Outreach',
    features: [
      { name: 'Contact & Lead Management', free: true, verified: true, partner: true, elite: true },
      { name: 'Email Campaigns (Unlimited)', free: false, verified: false, partner: true, elite: true },
      { name: 'SMS Marketing', free: false, verified: false, partner: '1,000/mo ($0.03 after)', elite: '5,000/mo ($0.03 after)' },
      { name: 'Email/SMS Templates', free: false, verified: false, partner: true, elite: true },
      { name: 'Power Dialer', free: false, verified: false, partner: true, elite: true },
      { name: 'Deal Pipeline & Sales Tracking', free: true, verified: true, partner: true, elite: true },
      { name: 'Customer Segmentation', free: false, verified: false, partner: true, elite: true },
      { name: 'Sale & Activity Tracking', free: false, verified: false, partner: true, elite: true },
      { name: 'Team Collaboration Tools', free: false, verified: false, partner: true, elite: true },
    ],
  },
  {
    category: 'Wine Intelligence (Wineries Only)',
    features: [
      { name: 'Wine Inventory Management', free: false, verified: false, partner: true, elite: true },
      { name: 'POS Integration', free: false, verified: false, partner: true, elite: true },
      { name: 'AI Tasting Notes Generator', free: false, verified: false, partner: true, elite: true },
      { name: 'Distribution & Wine AI Tools', free: false, verified: false, partner: true, elite: true },
    ],
  },
  {
    category: 'Analytics & Insights',
    features: [
      { name: 'Profile Analytics', free: false, verified: true, partner: true, elite: true },
      { name: 'Lead Source Tracking & Attribution', free: true, verified: true, partner: true, elite: true },
      { name: 'Conversion Tracking & ROI Reports', free: true, verified: true, partner: true, elite: true },
      { name: 'Competitive Benchmarking', free: false, verified: false, partner: true, elite: true },
      { name: 'Custom Reporting', free: false, verified: false, partner: true, elite: true },
      { name: 'Heatmaps & User Behavior', free: false, verified: false, partner: true, elite: true },
    ],
  },
  {
    category: 'Premium Services & Support',
    features: [
      { name: 'Priority Support', free: false, verified: true, partner: true, elite: true },
      { name: 'Category Exclusivity', free: false, verified: false, partner: false, elite: true },
      { name: 'White Label CRM', free: false, verified: false, partner: false, elite: true },
      { name: 'Guaranteed Leads (25/month)', free: false, verified: false, partner: true, elite: true },
      { name: 'Professional Photo/Video Production', free: false, verified: false, partner: false, elite: true },
      { name: 'Custom Integrations & API Access', free: false, verified: false, partner: false, elite: true },
      { name: 'Monthly Strategy Calls', free: false, verified: false, partner: true, elite: true },
    ],
  },
];
