export const TIER_FEATURES = {
  free: {
    showBasicListing: true,
    showAddress: true, showPhone: true, showWebsite: false, showEmail: false,
    showSocialLinks: false, showDescription: false, showHours: false,
    showImages: false, showVideo: false, showGoogleReviews: false,
    showGoogleMap: true, showBlog: false, showEvents: false,
    showJobs: false, showTeam: false,
    verifiedBadge: false, featuredPlacement: false,
    smartOfferFee: 0.30, leadsPerMonth: 0,
    aiAssistant: false, aiCallAssistant: false,
    emailCampaigns: false, smsCampaigns: false,
    categoryExclusivity: false, dedicatedManager: false,
    enteredInBusinessSweepstakes: false,
    maxImages: 0, maxSmartOffers: 0, hasAnalytics: false,
    hasLeadAlerts: false, platformFee: 0, setupFee: 0,
    maxDescriptionChars: 200, hasRichText: false, maxVideoEmbeds: 0,
    hasVirtualTour: false,
  },
  verified_platinum: {
    showBasicListing: true,
    showAddress: true, showPhone: true, showWebsite: true, showEmail: true,
    showSocialLinks: true, showDescription: true, showHours: true,
    showImages: true, showVideo: true, showGoogleReviews: true,
    showGoogleMap: true, showBlog: true, showEvents: true,
    showJobs: true, showTeam: true,
    verifiedBadge: true, featuredPlacement: false,
    smartOfferFee: 0.25, leadsPerMonth: 'AI-enhanced' as const,
    aiAssistant: true, aiCallAssistant: false,
    emailCampaigns: false, smsCampaigns: false,
    categoryExclusivity: false, dedicatedManager: false,
    enteredInBusinessSweepstakes: true,
    maxImages: 5, maxSmartOffers: 3, hasAnalytics: false,
    hasLeadAlerts: true, platformFee: 0.25, setupFee: 199,
    maxDescriptionChars: 1000, hasRichText: true, maxVideoEmbeds: 0,
    hasVirtualTour: false,
  },
  platinum_partner: {
    showBasicListing: true,
    showAddress: true, showPhone: true, showWebsite: true, showEmail: true,
    showSocialLinks: true, showDescription: true, showHours: true,
    showImages: true, showVideo: true, showGoogleReviews: true,
    showGoogleMap: true, showBlog: true, showEvents: true,
    showJobs: true, showTeam: true,
    verifiedBadge: true, featuredPlacement: true,
    smartOfferFee: 0.20, leadsPerMonth: 25,
    aiAssistant: true, aiCallAssistant: '$0.15/min' as const,
    emailCampaigns: true, smsCampaigns: '1000/mo' as const,
    categoryExclusivity: false, dedicatedManager: false,
    enteredInBusinessSweepstakes: true,
    maxImages: 15, maxSmartOffers: 10, hasAnalytics: true,
    hasLeadAlerts: true, platformFee: 0.20, setupFee: 499,
    maxDescriptionChars: 2500, hasRichText: true, maxVideoEmbeds: 1,
    hasVirtualTour: false,
  },
  platinum_elite: {
    showBasicListing: true,
    showAddress: true, showPhone: true, showWebsite: true, showEmail: true,
    showSocialLinks: true, showDescription: true, showHours: true,
    showImages: true, showVideo: true, showGoogleReviews: true,
    showGoogleMap: true, showBlog: true, showEvents: true,
    showJobs: true, showTeam: true,
    verifiedBadge: true, featuredPlacement: true,
    smartOfferFee: 0.20, leadsPerMonth: 'unlimited' as const,
    aiAssistant: true, aiCallAssistant: 'unlimited' as const,
    emailCampaigns: true, smsCampaigns: '5000/mo' as const,
    categoryExclusivity: true, dedicatedManager: true,
    enteredInBusinessSweepstakes: true,
    maxImages: 50, maxSmartOffers: -1, hasAnalytics: true,
    hasLeadAlerts: true, platformFee: 0.15, setupFee: 999,
    maxDescriptionChars: 5000, hasRichText: true, maxVideoEmbeds: -1,
    hasVirtualTour: true,
  },
} as const;

export type TierName = keyof typeof TIER_FEATURES;

export function getTierFeatures(tier: string) {
  return TIER_FEATURES[tier as TierName] || TIER_FEATURES.free;
}
