/**
 * Stripe Price IDs (TEST MODE)
 * Auto-generated by scripts/stripe-setup.ts
 * Do NOT edit manually — re-run the script to regenerate.
 */

// ── Subscription Prices ──

// Verified Platinum
export const PRICE_VERIFIED_MONTHLY = "price_1T2iUHPBhzmoITNuL6RUpsYD";
export const PRICE_VERIFIED_QUARTERLY = "price_1T2iUHPBhzmoITNuSlPfvHaJ";
export const PRICE_VERIFIED_6MONTH = "price_1T2iUHPBhzmoITNuoHbiuGLZ";
export const PRICE_VERIFIED_ANNUAL = "price_1T2iUHPBhzmoITNumKQJWLVp";

// Platinum Partner
export const PRICE_PARTNER_MONTHLY = "price_1T2iUIPBhzmoITNuq2nZdvlv";
export const PRICE_PARTNER_QUARTERLY = "price_1T2iUIPBhzmoITNuzuNyKMKk";
export const PRICE_PARTNER_6MONTH = "price_1T2iUJPBhzmoITNujmvp4LsQ";
export const PRICE_PARTNER_ANNUAL = "price_1T2iUJPBhzmoITNuZiV99rsp";

// Platinum Elite
export const PRICE_ELITE_MONTHLY = "price_1T2iUJPBhzmoITNulfiWDeFU";
export const PRICE_ELITE_QUARTERLY = "price_1T2iUKPBhzmoITNu8mSTz7LT";
export const PRICE_ELITE_6MONTH = "price_1T2iUKPBhzmoITNu2HRCB7J1";
export const PRICE_ELITE_ANNUAL = "price_1T2iUKPBhzmoITNupVNuPbWk";

// ── One-Time Setup Fees ──

export const PRICE_VERIFIED_SETUP = "price_1T2iULPBhzmoITNuGF6tfrQz";
export const PRICE_PARTNER_SETUP = "price_1T2iULPBhzmoITNuupOR8pyF";
export const PRICE_ELITE_SETUP = "price_1T2iUMPBhzmoITNuy4681qxi";

// ── Coupon Codes ──

export const COUPON_SETUP25 = "SETUP25";
export const COUPON_SETUP50 = "SETUP50";
export const COUPON_SETUP75 = "SETUP75";
export const COUPON_SETUPFREE = "SETUPFREE";

// ── Lookup Maps ──

export const SUBSCRIPTION_PRICES = {
  verified: {
    monthly: PRICE_VERIFIED_MONTHLY,
    quarterly: PRICE_VERIFIED_QUARTERLY,
    six_month: PRICE_VERIFIED_6MONTH,
    annual: PRICE_VERIFIED_ANNUAL,
  },
  partner: {
    monthly: PRICE_PARTNER_MONTHLY,
    quarterly: PRICE_PARTNER_QUARTERLY,
    six_month: PRICE_PARTNER_6MONTH,
    annual: PRICE_PARTNER_ANNUAL,
  },
  elite: {
    monthly: PRICE_ELITE_MONTHLY,
    quarterly: PRICE_ELITE_QUARTERLY,
    six_month: PRICE_ELITE_6MONTH,
    annual: PRICE_ELITE_ANNUAL,
  },
} as const;

export const SETUP_FEE_PRICES = {
  verified_setup: PRICE_VERIFIED_SETUP,
  partner_setup: PRICE_PARTNER_SETUP,
  elite_setup: PRICE_ELITE_SETUP,
} as const;
